# Generated by Django 3.1.1 on 2020-10-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201011_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='url',
            field=models.URLField(default='http://www.pythoneers.cn', verbose_name='视频链接'),
        ),
    ]
