# Generated by Django 3.1.1 on 2020-10-29 02:13

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20201011_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfo',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='机构详情'),
        ),
    ]
